### ISSUE TITLE
:status never in state

### ISSUE THREAD

**Issue by chrismurrph** [fulcrologic/websockets2-demo#4]
It seems like `op/long-running-thing` should change the "Status" on the screen but it never does. In fact there's no `:status` in the app state anywhere ever.

**Comment by awkay** [comment]
I agree that something in the pipeline seems broken. It looks like something got overlooked in the polish work that @currentoor helped with. Did I miss a merge or something?

**Comment by awkay** [comment]
I don't see anything obvious, though I did automate the plumbing in there somewhere, and it looks like the responses are adding in a bunch of mess that doesn't belong. This is a bug in Fulcro, I think

**Comment by awkay** [comment]
Well, strange. The data is coming back correctly. Just verified the plumbing is being called with the correct response.

**Comment by awkay** [comment]
See https://github.com/fulcrologic/fulcro/issues/168
